
- name: Install python3
  hosts: aws_ec2
  become: yes
  become_user:                                      #if not specifieced, root user will be considered
  tasks: 
    - name: Install python3
      yum:
        name: 
        - python3
        - docker
        update_cache: yes
        state: present  


- name: Install docker compose
  hosts: aws_ec2
  become: yes
  become_user:
  tasks: 
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-{{lookup('pipe', 'uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x


- name: Start docker and attach user ec2-user to docker group
  hosts: aws_ec2
  become: yes
  become_user:
  tasks: 
    - name: Start docker demon
      systemd:
        name: docker
        state: started
    - name: add ec2-user to docker group
      user: 
        name: ec2-user
        groups: docker
        append: yes 


- name: Start docker and attach user ec2-user to docker group
  hosts: aws_ec2
  tasks:   
  - name: test docker
    command: docker pull redis

    