
- name: Install java and net tools
  hosts: webserver
  tasks:
  - name: update
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  - name: Install java
    apt: name=openjdk-8-jre-headless
  - name: Install net tools
    apt: name=net-tools




- name: Download and unpack nexus
  hosts: webserver
  tasks:
  - name: Download nexus
    get_url: 
      url: https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.29.2-02-unix.tar.gz
      dest: /opt
    register: download_result                             # to reference the src destination despite of the version
  # - debug: msg={{download_result}}                       # used to print the message on the console and get the dest attribute 
  - name: untar nexus installer
    unarchive:
      src: "{{download_result.dest}}"
      dest: /opt/
      remote_src: true
  - name: find the folder
    find: 
      paths: /opt
      patterns: "nexus-*"
      file_type: directory
    register: file_name                            # to reference the src destination despite of the version
  - name: Check if nexus folder already there
    stat: 
      path: /opt/nexus
    register: stat_result
  - name: rename nexus folder
    shell: mv {{file_name.files[0].path}} /opt/nexus      #rename folder to nexus     
    when: not stat_result.stat.exists


- name: Create nexus user to own nexus folders
  hosts: webserver
  tasks:
  - name: Ensure group nexus group
    group:
      name: nexus
      state: present
  - name: Create nexus user
    user: 
      name: nexus
      group: nexus
  - name: make nexus user owner of folder nexus
    file: 
      path: /opt/nexus
      state: directory    
      owner: nexus
      group: nexus
      recurse: yes
  - name: make nexus user owner of folder nexus
    file: 
      path: /opt/sonatype-work
      state: directory    
      owner: nexus
      group: nexus
      recurse: yes      
    

- name: start nexus with nexus user 
  hosts: webserver
  become: true
  become_user: nexus
  tasks:
  - name:  set run_as_user nexus
    blockinfile:
      path: /opt/nexus/bin/nexus.rc
      block: |                #multiple line 
        run_as_user="nexus"
  - name: start nexus
    command: /opt/nexus/bin/nexus start
  

